# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import provider_pb2 as provider__pb2


class ResourceProviderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DiffConfig = channel.unary_unary(
                '/ResourceProvider/DiffConfig',
                request_serializer=provider__pb2.DiffRequest.SerializeToString,
                response_deserializer=provider__pb2.DiffResponse.FromString,
                )


class ResourceProviderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def DiffConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ResourceProviderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DiffConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DiffConfig,
                    request_deserializer=provider__pb2.DiffRequest.FromString,
                    response_serializer=provider__pb2.DiffResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ResourceProvider', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ResourceProvider(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def DiffConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ResourceProvider/DiffConfig',
            provider__pb2.DiffRequest.SerializeToString,
            provider__pb2.DiffResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
